server:
  port: 8080  # default port
spring:
  application:
    name: tiger_takeaway  # 应用名称

  # 数据库信息|必填
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      # 本人将使用服务器启动项填写以下敏感信息 #
      # IDEA->Run->Edit Configurations->Environment Variables->添加以下变量 #
      url: jdbc:mysql://localhost:3306/tiger_takeaway?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      username: tiger_dev
      password: password

  # 邮箱验证配置信息
  mail:
    host: smtp.gmail.com
    username: # 请自行配置邮箱地址
    password: mwluvwkrszbldgbh # 请自行配置邮箱smtp授权码 具体请看本项目根目录下的README.md
    port: 587
    default-encoding: UTF-8
    timeout: 60 # 验证码有效时间 单位：分钟
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        # 开启debug以后，邮件发送过程的日志会在控制台上打印出来
        debug: true

mybatis-plus:
  configuration:
    # 在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID

# 其它配置信息
tiger:
  # 文件存储位置信息|必填
  filesPath: img # 本地测试时，文件存储路径，img的在Resources后的相对路径